name: CI-CD

on:
  push:
    branches:
    - main
    - github-actions-test
    paths:
    - '**.py'
    - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
    - '**.py'
    - '.github/workflows/lint.yml'
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies [pip]
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name : Check Black
        run: |
          black . --check

      - name : Check Isort
        run: |
          isort --profile black --check .

  test:
    needs: lint
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Install and test package on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package [pip]
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests with Pytest
        run: |
          coverage run -m pytest

      - name: Coverage
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        run: |
          coverage report
          coverage json

      - name: Upload coverage artifact
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.json

      - name: Metadata check
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        run: |
          python .github/scripts/metadata_checker

  upload-coverage:
    runs-on: ubuntu-latest
    needs: test
    name: Upload coverage report to Codecov
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}


